### ISSUE TITLE
Cancelled eunit tests causing test failure

### ISSUE THREAD

**Issue by oubiwann** [mojombo/mustache.erl#19]
With the introduction of the new tests in change 2e0227b, the eunit tests no longer complete successfully. There are no reported unit test failures, however tests are canceled and ``make test`` returns non-zero. The offending test function is ``get_from_module_test_``.

Using meck 0.7.2 (the release that was available when mustache.erl was last developed heavily), the following context setup errors are reported in change 2e0227b:

```erlang
undefined
*** context setup failed ***
**in function meck:new/1
  called as new(mock_module)
in call from mustache_ctx_tests:'-get_from_module_test_/0-fun-0-'/0 
  (test/mustache_ctx_tests.erl, line 56)
**error:undef


undefined
*** context setup failed ***
**in function meck:new/1
  called as new(mock_module)
in call from mustache_ctx_tests:'-get_from_module_test_/0-fun-0-'/0 
  (test/mustache_ctx_tests.erl, line 56)
**error:undef


undefined
*** context setup failed ***
**in function meck:new/1
  called as new(mock_module)
in call from mustache_ctx_tests:'-get_from_module_test_/0-fun-0-'/0 
  (test/mustache_ctx_tests.erl, line 56)
**error:undef
```

Rolling back to change 94eb716 (the change right before the one that introduced the cancelled test errors), all tests pass.

**Comment by lemenkov** [comment]
@pusewicz I think it's safe to close this for now.

**Comment by pusewicz** [comment]
Thanks!
