### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by fa-gdc** [mojombo/mustache.erl#21]
Could you please tag some of the newer commits as a release?
I'm trying to package rebar 2.6.0 for Fedora and it bundles some old version of this library (but not the v0.1.0 though). Since bundling 3rd party libraries is kind of frowned upon among Fedora packagers I thought I would make a new package of this library as well, add it as a package dependency and remove the source code from rebar. Therefore Fedora will get not only the newest rebar but mustache as well.
Many thanks!

**Comment by pusewicz** [comment]
Done! https://github.com/mojombo/mustache.erl/tree/v0.1.1
